logging:
  pattern:
    file: "%d{yyyy年MM月dd日HH:MM:SS}    %level    %class.%thread:%line    {{%m}}%n"
    console: "%d{yyyy年MM月dd日HH:MM:SS}    %level    %class.%thread:%line    {{%m}}%n"
  file:
    name: src/main/resources/main.log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-jquwixob.sql.tencentcdb.com:29396/users
    username: "root"
    password: "3.1415926535zxc"


